### ISSUE TITLE
contact 

### ISSUE THREAD

**Issue by oceanBigOne** [romaindurand/maju.app#13]
Bonjour,

Nous avons essayé de faire une petite webconf entre développeurs autour du JM avec l'association MieuxVoter. L'idée était de mutualiser nos efforts et/ou faire des liens entre nos différentes plateforme.
Nous avons parler de maju.app (entre autre). Serais-tu intéresser pour rejoindre nos discussions ?

Si oui, je ne sais pas comment on peut discuter en MP via github ^^

**Comment by romaindurand** [comment]
Via [twitter](https://twitter.com/romaindurand) ou [facebook](https://www.facebook.com/romaindurand89) ça devrait être plus pratique, mais oui, carrément intéressé ! Vous utilisez quoi pour les webconf ? Pour de l'audio + texte, [discord](http://discordapp.com/) est vraiment sympa 😃
